node('master')

{

stage('ContinuousDownload_loans')
         {
    git 'https://github.com/tharun957/Firstwebapp.git'
        }

stage('Continuousbuild_loans')
         {
   sh label: '', script: 'mvn package'
        }

}
